data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018
  holdout_year: 2021-2022

model:
  target: xg
  numerical_features:
    - round
    - poss
    - days_till_next
    - days_since_last
    - att_total
    - home_att_total
    - away_att_total
    # - def_total
    # - home_def_total
    # - away_def_total
    # - date
    # - xga
  categorical_features:
    - venue
    - team
    - opponent
  group_by: season
  baseline_columns:
    - xg_ma
    - team_odds_2_score
    - att_total
  random_seed: 42
  xgboost_params:
    base_score: 0.5
    n_estimators: 10
    early_stopping_rounds: 5
    objective: reg:squarederror
    learning_rate: 0.01
    eval_metric: mae

housekeeping:
  to_keep: 10
# hyperopt:
#   target:
#     name: pipeline_output
#     max_trials: 5
#     strategy: min
#   model:
#     xgboost_params:
#       early_stopping_rounds:
#         method: uniform
#         low: 5
#         high: 30
