model:
  target: xg
  numerical_features:
    - round
    - poss
    - days_till_next
    - days_since_last
    - att_total
    - home_att_total
    - away_att_total
    - pts_b4_match
    - rank_b4_match
    - pts_gap_above
    - pts_gap_below
    # - def_total
    # - home_def_total
    # - away_def_total
    # - date
    # - xga
  categorical_features:
    - venue
    - team
    - opponent
  group_by: season
  baseline_columns:
    - xg_ma
    - team_odds_2_score
    - att_total
  pca_components: 2
  random_state: 42
  verbose: false
  n_jobs: null
  sort_models: r2
  models:
    - huber
    - ridge
    - lr
    - gbr
    - rf
  model_weights: [1, 1, 1, 1, 1]
  huber_params:
    alpha: 0.99
    epsilon: 2.00
    fit_intercept: True
  ridge_params:
    alpha: 9.99
  lr_params:
    fit_intercept: True
  gbr_params:
    n_estimators: 233
    learning_rate: 0.068
    subsample: 0.88
    min_samples_split: 7
    max_depth: 1
    max_features: 0.63
    min_impurity_decrease: 0.011
    n_iter_no_change: null
  rf_params:
    n_estimators: 158
    max_depth: 8
    min_impurity_decrease: 0.0024
    max_features: 0.43
    bootstrap: True

# hyperopt:
#   target:
#     name: val_score
#     max_trials: 5
#     strategy: max
#     algo: tpe
#     early_termination: null
#   groups:
#     model:
#       models:
#         - [huber]
#         - [ridge]
#         - [lr]
#   0:
#     model:
#       huber_params:
#         epsilon:
#           method: uniform
#           low: 1
#           high: 2
#         alpha:
#           method: uniform
#           low: 0.0000000001
#           high: 0.9999999999
#         fit_intercept:
#           method: choice
#           values: [True, False]
# #   1:
#     model:
#       ridge_params:
#         alpha:
#           method: uniform
#           low: 0.001
#           high: 10
#         fit_intercept:
#           method: choice
#           values: [True, False]
#   2:
#     model:
#       lr_params:
#         fit_intercept: 
#           method: choice
#           values: [True, False]



######################################

data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018
  holdout_year: 2021-2022

######################################

housekeeping:
  to_keep: 30
  keep_model_best: 3
  metric: val_r2
  strategy: max

######################################

optimization:
  team_id: 3531385
  ft: 1
  horizon: 3
  tr_horizon: 2
  wc_on: 8
  bb_on: null
  fh_on: null
  timeout: 60
  log: false
  decay: 0.5
  ft_bonus: 1.5
  itb_bonus: 0.08
  bench_weights: {0: 0.03, 1: 0.21, 2: 0.06, 3: 0.002}
  solver: cplex
  backtest_player_history: true
  backtest_players:
    Me: 3531385
    Hazard: 1195527
    FPL Raptor: 5431
    Donald: 307190