data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  test_size: 0.2
  random_seed: 42
  start_year: 2017-2018
# hyperopt:
#   target:
#     name: correlation
#     max_trials: 10
#     strategy: max
#   data:
#     # elo_learning_rate:
#     #   method: uniform
#     #   low: 0.1
#     #   high: 0.2
#     home_away_weight:
#       method: uniform
#       low: 0.4
#       high: 0.6
