model:
  target: xg
  numerical_features:
    - round
    - poss
    - days_till_next
    - days_since_last
    - att_total
    - home_att_total
    - away_att_total
    # - def_total
    # - home_def_total
    # - away_def_total
    # - date
    # - xga
  categorical_features:
    - venue
    - team
    - opponent
  group_by: season
  baseline_columns:
    - xg_ma
    - team_odds_2_score
    - att_total
  random_seed: 42
  pca_components: 3
  early_stopping_rounds: 5
  verbose: false
  sort_models: r2
  models:
    - huber
    - ridge
    - lr
    - gbr
    - rf
  model_weights: [1]
  huber_params:
    alpha: 0.0001
    epsilon: 1.35
    fit_intercept: True
    max_iter: 100
    tol: 1.0e-05
    warm_start: False
  ridge_params:
    alpha: 1.0
    copy_X: True
    fit_intercept: True
    max_iter: null
    positive: False
    random_state: null
    solver: auto
    tol: 0.0001
  lr_params:
    copy_X: True
    fit_intercept: True
    n_jobs: null
    positive: False
  gbr_params:
    alpha: 0.9
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.1
    loss: squared_error
    max_depth: 3
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 100
    n_iter_no_change: null
    random_state: null
    subsample: 1.0
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: False
  rf_params:
    bootstrap: True
    ccp_alpha: 0.0
    criterion: squared_error
    max_depth: null
    max_features: 1.0
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 100
    n_jobs: null
    oob_score: False
    random_state: null
    verbose: 0
    warm_start: False
hyperopt:
  target:
    name: val_score
    max_trials: 4
    strategy: max
    algo: tpe
    early_termination: null
  groups:
    model:
      models:
        - [huber]
        - [ridge]
  0:
    model:
      huber_params:
        alpha: 
          method: loguniform
          low:  0.0001
          high: 1
        epsilon: 
          method: uniform
          low: 1
          high: 2
  1:
    model:
      ridge_params:
        alpha: 
          method: loguniform
          low:  0.0001
          high: 100
        normalize: 
          method: choice
          values:  
            - true
            - false

        # - [lr: 1]
        # - [gbr: 1]
        # - [rf: 1]
    # xgboost_params:
    #   learning_rate:
    #     method: uniform
    #     low:  0.01
    #     high: 0.1
    #   n_estimators:
    #     method: quniform
    #     low: 10
    #     high: 100
    #     q: 1

######################################

data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018
  holdout_year: 2021-2022

######################################

housekeeping:
  to_keep: 30

######################################

optimization:
  team_id: 3531385
  ft: 1
  horizon: 3
  tr_horizon: 2
  wc_on: 8
  bb_on: null
  fh_on: null
  timeout: 60
  log: false
  decay: 0.5
  ft_bonus: 1.5
  itb_bonus: 0.08
  bench_weights: {0: 0.03, 1: 0.21, 2: 0.06, 3: 0.002}
  solver: cplex
  backtest_player_history: true
  backtest_players:
    Me: 3531385
    Hazard: 1195527
    FPL Raptor: 5431
    Donald: 307190