data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018
  holdout_year: 2021-2022

model:
  target: xg
  numerical_features:
    - round
    - poss
    - days_till_next
    - days_since_last
    - att_total
    - home_att_total
    - away_att_total
    # - def_total
    # - home_def_total
    # - away_def_total
    # - date
    # - xga
  categorical_features:
    - venue
    - team
    - opponent
  group_by: season
  baseline_columns:
    - xg_ma
    - team_odds_2_score
    - att_total
  random_seed: 42
  xgboost_params:
    base_score: 0.5
    n_estimators: 10
    early_stopping_rounds: 5
    objective: reg:squarederror
    learning_rate: 0.01
    eval_metric: mae

housekeeping:
  to_keep: 10

optimization:
  team_id: 3531385
  ft: 1
  horizon: 3
  tr_horizon: 2
  wc_on: 8
  bb_on: null
  fh_on: null
  timeout: 60
  log: false
  decay: 0.5
  ft_bonus: 1.5
  itb_bonus: 0.08
  bench_weights: {0: 0.03, 1: 0.21, 2: 0.06, 3: 0.002}
  solver: cplex
  backtest_players:
    # Me: 3531385
    Hazard: 1195527
    # FPL Raptor: 5431
    Donald: 307190
# hyperopt:
#   target:
#     name: pipeline_output
#     max_trials: 5
#     strategy: min
#   model:
#     xgboost_params:
#       early_stopping_rounds:
#         method: uniform
#         low: 5
#         high: 30
