model:
  target: xg
  numerical_features:
    - round
    - poss
    - days_till_next
    - days_since_last
    - att_total
    - home_att_total
    - away_att_total
    # - def_total
    # - home_def_total
    # - away_def_total
    # - date
    # - xga
  categorical_features:
    - venue
    - team
    - opponent
  group_by: season
  baseline_columns:
    - xg_ma
    - team_odds_2_score
    - att_total
  random_seed: 42
  pca_components: 3
  early_stopping_rounds: 5
  verbose: false
  sort_models: r2
  models:
    # - huber
    # - ridge
    # - lr
    # - gbr
    - rf
  model_weights: [1, 1, 1, 1, 1]
  huber_params:
    alpha: 2.71
    epsilon: 1.97
    fit_intercept: True
  ridge_params:
    alpha: 2.72
  lr_params:
    fit_intercept: True
  gbr_params:
    n_estimators: 21
    learning_rate: 1.22
    subsample: 0.70
    min_samples_split: 7
    max_depth: 1
    max_features: 0.73
    min_impurity_decrease: 1.34
  rf_params:
    n_estimators: 1000
    max_depth: 7
    min_impurity_decrease: 1.12
    max_features: 0.99
    bootstrap: True

# hyperopt:
#   target:
#     name: val_score
#     max_trials: 100
#     strategy: max
#     algo: tpe
#     early_termination: null
# #   groups:
# #     model:
# #       models:
# #         - [gbr]
# #         - [rf]
#   0:
#     model:
#       rf_params:
#         n_estimators: 
#           method: uniform
#           scope: int
#           low: 10
#           high: 300
#         max_depth: 
#           method: uniform
#           scope: int
#           low: 1
#           high: 11
#         min_impurity_decrease: 
#           method: loguniform
#           low: 0.000000001
#           high: 0.5
#         max_features: 
#           method: uniform
#           low: 0.4
#           high: 1
#         bootstrap:
#           method: choice
#           values: [true, false]

######################################

data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018
  holdout_year: 2021-2022

######################################

housekeeping:
  to_keep: 30
  keep_model_best: 3
  metric: val_r2
  strategy: max

######################################

optimization:
  team_id: 3531385
  ft: 1
  horizon: 3
  tr_horizon: 2
  wc_on: 8
  bb_on: null
  fh_on: null
  timeout: 60
  log: false
  decay: 0.5
  ft_bonus: 1.5
  itb_bonus: 0.08
  bench_weights: {0: 0.03, 1: 0.21, 2: 0.06, 3: 0.002}
  solver: cplex
  backtest_player_history: true
  backtest_players:
    Me: 3531385
    Hazard: 1195527
    FPL Raptor: 5431
    Donald: 307190