data:
  elo_learning_rate: 0.1
  home_away_weight: 0.5
  start_year: 2017-2018

model:
  target: XG
  numerical_features:
    - ROUND
    - POSS
    - DAYS_TILL_NEXT
    - DAYS_SINCE_LAST
    - ATT_TOTAL
    - HOME_ATT_TOTAL
    - AWAY_ATT_TOTAL
    # - DEF_TOTAL
    # - HOME_DEF_TOTAL
    # - AWAY_DEF_TOTAL
    # - DATE
    # - XGA
  categorical_features:
    - VENUE
    - TEAM
    - OPPONENT
  group_by: SEASON
  random_seed: 42
  xgboost_params:
    base_score: 0.5
    n_estimators: 1000
    early_stopping_rounds: 50
    objective: reg:squarederror
    learning_rate: 0.01
    eval_metric: mae

  
# hyperopt:
#   target:
#     name: correlation
#     max_trials: 10
#     strategy: max
#   data:
#     # elo_learning_rate:
#     #   method: uniform
#     #   low: 0.1
#     #   high: 0.2
#     home_away_weight:
#       method: uniform
#       low: 0.4
#       high: 0.6
