DROP TABLE IF EXISTS TEAM_MATCH_LOG;

CREATE TABLE TEAM_MATCH_LOG(
    SEASON TEXT,
    TEAM TEXT,
    DATE TEXT,
    TIME TEXT,
    COMP TEXT,
    ROUND TEXT,
    DAY TEXT,
    VENUE TEXT,
    RESULT TEXT,
    GF INTEGER,
    GA INTEGER,
    OPPONENT TEXT,
    XG REAL,
    XGA REAL,
    POSS INTEGER,
    LINK TEXT
);

CREATE UNIQUE INDEX SEASON_TEAM_DATE_OPPONENT_PK
ON TEAM_MATCH_LOG(SEASON, TEAM, DATE, OPPONENT);