model:
  variance_threshold: 0.02
  f_test_method: spearmanr
  f_test_threshold: 0.15
  target: fpl_points
  baseline_columns: [fpl_points_ma5]
  not_features:
    - id
    - fpl_name
    - date
    - player
  categorical_features:
    - team
    - opponent
    - venue
    - pos
  numerical_features:
    - round
    - value
    - total_att_elo
    - home_total_att_elo
    - away_total_att_elo
    - total_def_elo
    - home_total_def_elo
    - away_total_def_elo
    - pts_b4_match
    - rank_b4_match
    - pts_gap_above
    - pts_gap_below
    - min_ma5
    - gls_ma5
    - ast_ma5
    - pk_ma5
    - pkatt_ma5
    - sh_ma5
    - sot_ma5
    - touches_ma5
    - xg_ma5
    - npxg_ma5
    - xag_ma5
    - sca_ma5
    - gca_ma5
    - sota_ma5
    - ga_ma5
    - saves_ma5
    - savepct_ma5
    - cs_ma5
    - psxg_ma5
    - team_poss_ma5
    - team_gf_ma5
    - team_ga_ma5
    - team_xg_ma5
    - team_xga_ma5
    - fpl_points_ma5
    - value_ma5
    - total_att_elo_ma5
    - home_total_att_elo_ma5
    - away_total_att_elo_ma5
    - total_def_elo_ma5
    - home_total_def_elo_ma5
    - away_total_def_elo_ma5
    - match_points_ma5
    - league_points_ma5
  group_by: season
  pca_components: 7
  random_state: 42
  verbose: false
  n_jobs: null
  sort_models: r2
  models:
    - lightgbm
    - gbr
    - ridge
    - lr
    - xgboost
  model_weights: [1, 1, 1, 1, 1]

  lightgbm_params:
    num_leaves: 3
    learning_rate: 0.19
    n_estimators: 237
    min_split_gain: 0.97
    reg_alpha: 0.00035
    reg_lambda: 0.96
    feature_fraction: 0.76
    bagging_fraction: 0.89
    bagging_freq: 1
    min_child_samples: 78

  gbr_params:
    n_estimators: 242
    learning_rate: 0.168
    subsample: 0.75
    min_samples_split: 2
    max_depth: 2
    max_features: 0.80
    min_impurity_decrease: 0.00013
    n_iter_no_change: null

  ridge_params:
    alpha: 6.43

  lr_params:
    fit_intercept: True

  xgboost_params:
    learning_rate: 0.056
    n_estimators: 151
    subsample: 0.60
    max_depth: 7
    colsample_bytree: 0.81
    min_child_weight: 2
    reg_alpha: 5.27
    reg_lambda: 2.07
    scale_pos_weight: 1.63
