model:
  variance_threshold: 0.02
  f_test_method: spearmanr
  f_test_threshold: 0.15
  target: fpl_points
  baseline_columns: [fpl_points_ma5]
  not_features:
    - id
    - fpl_name
    - date
    - player
  categorical_features:
    - team
    - opponent
    - venue
    - pos
  numerical_features:
    - round
    - value
    - total_att_elo
    - home_total_att_elo
    - away_total_att_elo
    - total_def_elo
    - home_total_def_elo
    - away_total_def_elo
    - pts_b4_match
    - rank_b4_match
    - pts_gap_above
    - pts_gap_below
    - min_ma5
    - gls_ma5
    - ast_ma5
    - pk_ma5
    - pkatt_ma5
    - sh_ma5
    - sot_ma5
    - touches_ma5
    - xg_ma5
    - npxg_ma5
    - xag_ma5
    - sca_ma5
    - gca_ma5
    - sota_ma5
    - ga_ma5
    - saves_ma5
    - savepct_ma5
    - cs_ma5
    - psxg_ma5
    - team_poss_ma5
    - team_gf_ma5
    - team_ga_ma5
    - team_xg_ma5
    - team_xga_ma5
    - fpl_points_ma5
    - value_ma5
    - total_att_elo_ma5
    - home_total_att_elo_ma5
    - away_total_att_elo_ma5
    - total_def_elo_ma5
    - home_total_def_elo_ma5
    - away_total_def_elo_ma5
    - match_points_ma5
    - league_points_ma5
  group_by: season
  pca_components: 7
  random_state: 42
  verbose: false
  n_jobs: null
  sort_models: mae
  models:
    - lightgbm
    - gbr
    - ridge
    - lr
    - xgboost
  model_weights: [1, 1, 1, 1, 1]

  lightgbm_params:
    num_leaves: 75
    learning_rate: 0.0186
    n_estimators: 287
    min_split_gain: 0.452
    reg_alpha: 0.018
    reg_lambda: 1.71
    feature_fraction: 0.56
    bagging_fraction: 0.9
    bagging_freq: 4
    min_child_samples: 58

  gbr_params:
    n_estimators: 251
    learning_rate: 0.0235
    subsample: 0.045
    min_samples_split: 9
    min_samples_leaf: 1
    max_depth: 5
    max_features: 0.5
    min_impurity_decrease: 0.21
    n_iter_no_change: null

  ridge_params:
    alpha: 9.98

  lr_params:
    fit_intercept: True

  xgboost_params:
    learning_rate: 0.04
    n_estimators: 270
    subsample: 0.349
    max_depth: 3
    colsample_bytree: 0.795
    min_child_weight: 1
    reg_alpha: 2.0
    reg_lambda: 4.2
    scale_pos_weight: 4.55
